import { IrregularVerb } from "../modules/irregularVerbs/entities/IrregularVerb";

const IrregularVerbDatabase: Array<IrregularVerb> = [
  new IrregularVerb({
    id: 1,
    translation: "S'er/Estar",
    infinitve: "To be",
    past: "Was/Were",
    pastParticiple: "Been",
    audioName: "to_be.mp3",
  }),
  new IrregularVerb({
    id: 2,
    translation: "Tornar-se",
    infinitve: "To become",
    past: "Became",
    pastParticiple: "Become",
    audioName: "to_become.mp3",
  }),
  new IrregularVerb({
    id: 3,
    translation: "Começar",
    infinitve: "To begin",
    past: "Began",
    pastParticiple: "Begun",
    audioName: "to_begin.mp3",
  }),
  new IrregularVerb({
    id: 4,
    translation: "Apostar",
    infinitve: "To bet",
    past: "Bet",
    pastParticiple: "Bet",
    audioName: "to_bet.mp3",
  }),
  new IrregularVerb({
    id: 5,
    translation: "Morder",
    infinitve: "To bite",
    past: "Bit",
    pastParticiple: "Bitten",
    audioName: "to_bite.mp3",
  }),
  new IrregularVerb({
    id: 6,
    translation: "Soprar",
    infinitve: "To blow",
    past: "Blew",
    pastParticiple: "Blown",
    audioName: "to_bet.mp3",
  }),
  new IrregularVerb({
    id: 7,
    translation: "Quebrar",
    infinitve: "To break",
    past: "Broke",
    pastParticiple: "Broken",
    audioName: "to_break.mp3",
  }),
  new IrregularVerb({
    id: 8,
    translation: "Trazer",
    infinitve: "To bring",
    past: "Brought",
    pastParticiple: "Brougth",
    audioName: "to_bring.mp3",
  }),
  new IrregularVerb({
    id: 9,
    translation: "Construir",
    infinitve: "To build",
    past: "Built",
    pastParticiple: "Built",
    audioName: "to_build.mp3",
  }),
  new IrregularVerb({
    id: 10,
    translation: "Comprar",
    infinitve: "To buy",
    past: "Bought",
    pastParticiple: "Bought",
    audioName: "to_buy.mp3",
  }),
  new IrregularVerb({
    id: 11,
    translation: "Pegar",
    infinitve: "To catch",
    past: "Caught",
    pastParticiple: "Caught",
    audioName: "to_catch.mp3",
  }),
  new IrregularVerb({
    id: 12,
    translation: "Escolher",
    infinitve: "To choose",
    past: "Chose",
    pastParticiple: "Chosen",
    audioName: "to_choose.mp3",
  }),
  new IrregularVerb({
    id: 13,
    translation: "Vir",
    infinitve: "To come",
    past: "Came",
    pastParticiple: "Come",
    audioName: "to_come.mp3",
  }),
  new IrregularVerb({
    id: 14,
    translation: "Custar",
    infinitve: "To cost",
    past: "Cost",
    pastParticiple: "Cost",
    audioName: "to_cost.mp3",
  }),
  new IrregularVerb({
    id: 15,
    translation: "Cortar",
    infinitve: "To cut",
    past: "Cut",
    pastParticiple: "Cut",
    audioName: "to_cut.mp3",
  }),
  new IrregularVerb({
    id: 16,
    translation: "Fazer",
    infinitve: "To do",
    past: "Did",
    pastParticiple: "Done",
    audioName: "to_do.mp3",
  }),
  new IrregularVerb({
    id: 17,
    translation: "Beber",
    infinitve: "To drink",
    past: "Drank",
    pastParticiple: "Drunk",
    audioName: "to_drink.mp3",
  }),
  new IrregularVerb({
    id: 18,
    translation: "Dirigir",
    infinitve: "To drive",
    past: "Drove",
    pastParticiple: "Driven",
    audioName: "to_drive.mp3",
  }),
  new IrregularVerb({
    id: 19,
    translation: "Comer",
    infinitve: "To eat",
    past: "Ate",
    pastParticiple: "Eaten",
    audioName: "to_eat.mp3",
  }),
  new IrregularVerb({
    id: 20,
    translation: "Cair",
    infinitve: "To fall",
    past: "Fell",
    pastParticiple: "Fallen",
    audioName: "to_fall.mp3",
  }),
  new IrregularVerb({
    id: 21,
    translation: "Sentir",
    infinitve: "To fell",
    past: "Felt",
    pastParticiple: "Felt",
    audioName: "to_fell.mp3",
  }),
  new IrregularVerb({
    id: 22,
    translation: "Alimentar",
    infinitve: "To feed",
    past: "Fed",
    pastParticiple: "Fed",
    audioName: "to_feed.mp3",
  }),
  new IrregularVerb({
    id: 23,
    translation: "Lutar",
    infinitve: "To fight",
    past: "Fought",
    pastParticiple: "Fought",
    audioName: "to_fight.mp3",
  }),
  new IrregularVerb({
    id: 24,
    translation: "Encontrar",
    infinitve: "To find",
    past: "Found",
    pastParticiple: "Found",
    audioName: "to_find.mp3",
  }),
  new IrregularVerb({
    id: 25,
    translation: "Voar / Pilotar",
    infinitve: "To fly",
    past: "Flew",
    pastParticiple: "Flown",
    audioName: "to_fly.mp3",
  }),
  new IrregularVerb({
    id: 26,
    translation: "Esquecer",
    infinitve: "To forget",
    past: "Forgot",
    pastParticiple: "Forgotten",
    audioName: "to_forget.mp3",
  }),
  new IrregularVerb({
    id: 27,
    translation: "Obter / Conseguir",
    infinitve: "To get",
    past: "Got",
    pastParticiple: "Got/Gotten",
    audioName: "to_get.mp3",
  }),
  new IrregularVerb({
    id: 28,
    translation: "Dar",
    infinitve: "To give",
    past: "Gave",
    pastParticiple: "Given",
    audioName: "to_give.mp3",
  }),
  new IrregularVerb({
    id: 29,
    translation: "Ir",
    infinitve: "To go",
    past: "Went",
    pastParticiple: "Gone",
    audioName: "to_go.mp3",
  }),
  new IrregularVerb({
    id: 30,
    translation: "Crescer",
    infinitve: "To grow",
    past: "Grew",
    pastParticiple: "Grown",
    audioName: "to_grow.mp3",
  }),
  new IrregularVerb({
    id: 31,
    translation: "Ter",
    infinitve: "To have",
    past: "had",
    pastParticiple: "Had",
    audioName: "to_have.mp3",
  }),
  new IrregularVerb({
    id: 32,
    translation: "Ouvir",
    infinitve: "To hear",
    past: "Heard",
    pastParticiple: "Heard",
    audioName: "to_hear.mp3",
  }),
  new IrregularVerb({
    id: 33,
    translation: "Esconder",
    infinitve: "To hide",
    past: "Hid",
    pastParticiple: "Hidden",
    audioName: "to_hide.mp3",
  }),
  new IrregularVerb({
    id: 34,
    translation: "Segurar",
    infinitve: "To hold",
    past: "Held",
    pastParticiple: "Held",
    audioName: "to_hold.mp3",
  }),
  new IrregularVerb({
    id: 35,
    translation: "Ferir",
    infinitve: "To hurt",
    past: "Hurt",
    pastParticiple: "Hurt",
    audioName: "to_hurt.mp3",
  }),
  new IrregularVerb({
    id: 36,
    translation: "Bater",
    infinitve: "To hit",
    past: "Hit",
    pastParticiple: "Hit",
    audioName: "to_hit.mp3",
  }),
  new IrregularVerb({
    id: 37,
    translation: "Guardar / Continuar",
    infinitve: "To keep",
    past: "Kept",
    pastParticiple: "Kept",
    audioName: "to_keep.mp3",
  }),
  new IrregularVerb({
    id: 38,
    translation: "Saber / Conhecer",
    infinitve: "To know",
    past: "Knew",
    pastParticiple: "Known",
    audioName: "to_know.mp3",
  }),
  new IrregularVerb({
    id: 39,
    translation: "Conduzir",
    infinitve: "To lead",
    past: "Led",
    pastParticiple: "Led",
    audioName: "to_lead.mp3",
  }),
  new IrregularVerb({
    id: 40,
    translation: "Sair / Deixar",
    infinitve: "To leave",
    past: "Left",
    pastParticiple: "Left",
    audioName: "to_leave.mp3",
  }),
  new IrregularVerb({
    id: 41,
    translation: "Emprestar",
    infinitve: "To lend",
    past: "Lent",
    pastParticiple: "Lent",
    audioName: "to_lend.mp3",
  }),
  new IrregularVerb({
    id: 42,
    translation: "Permitir / Deixar",
    infinitve: "To let",
    past: "Let",
    pastParticiple: "Let",
    audioName: "to_let.mp3",
  }),
  new IrregularVerb({
    id: 43,
    translation: "Perder",
    infinitve: "To lose",
    past: "Lost",
    pastParticiple: "Lost",
    audioName: "to_lose.mp3",
  }),
  new IrregularVerb({
    id: 44,
    translation: "Fazer",
    infinitve: "To make",
    past: "Made",
    pastParticiple: "Made",
    audioName: "to_make.mp3",
  }),
  new IrregularVerb({
    id: 45,
    translation: "Significar",
    infinitve: "To mean",
    past: "Meant",
    pastParticiple: "Meant",
    audioName: "to_mean.mp3",
  }),
  new IrregularVerb({
    id: 46,
    translation: "Encontrar",
    infinitve: "To meet",
    past: "Met",
    pastParticiple: "Met",
    audioName: "to_meet.mp3",
  }),
  new IrregularVerb({
    id: 47,
    translation: "Pagar",
    infinitve: "To pay",
    past: "Paid",
    pastParticiple: "Paid",
    audioName: "to_pay.mp3",
  }),
  new IrregularVerb({
    id: 48,
    translation: "Colocar / Pôr",
    infinitve: "To put",
    past: "Put",
    pastParticiple: "Put",
    audioName: "to_put.mp3",
  }),
  new IrregularVerb({
    id: 49,
    translation: "Ler",
    infinitve: "To read",
    past: "Read",
    pastParticiple: "Read",
    audioName: "to_read.mp3",
  }),
  new IrregularVerb({
    id: 50,
    translation: "Andar de",
    infinitve: "To ride",
    past: "Rode",
    pastParticiple: "Ridden",
    audioName: "to_ride.mp3",
  }),
  new IrregularVerb({
    id: 51,
    translation: "Tocar / Soar",
    infinitve: "To ring",
    past: "Rang",
    pastParticiple: "Rung",
    audioName: "to_ring.mp3",
  }),
  new IrregularVerb({
    id: 52,
    translation: "Elevar-se / Subir",
    infinitve: "To rise",
    past: "Rose",
    pastParticiple: "Risen",
    audioName: "to_rise.mp3",
  }),
  new IrregularVerb({
    id: 53,
    translation: "Correr",
    infinitve: "To run",
    past: "Ran",
    pastParticiple: "Run",
    audioName: "to_run.mp3",
  }),
  new IrregularVerb({
    id: 54,
    translation: "Dizer",
    infinitve: "To say",
    past: "Said",
    pastParticiple: "Said",
    audioName: "to_say.mp3",
  }),
  new IrregularVerb({
    id: 55,
    translation: "Ver",
    infinitve: "To see",
    past: "Saw",
    pastParticiple: "Seen",
    audioName: "to_see.mp3",
  }),
  new IrregularVerb({
    id: 56,
    translation: "Vender",
    infinitve: "To sell",
    past: "Sold",
    pastParticiple: "Sold",
    audioName: "to_sell.mp3",
  }),
  new IrregularVerb({
    id: 57,
    translation: "Enviar / Remeter",
    infinitve: "To send",
    past: "Sent",
    pastParticiple: "Sent",
    audioName: "to_send.mp3",
  }),
  new IrregularVerb({
    id: 58,
    translation: "Sacodir",
    infinitve: "To shake",
    past: "Shook",
    pastParticiple: "Shaken",
    audioName: "to_shake.mp3",
  }),
  new IrregularVerb({
    id: 59,
    translation: "Atirar",
    infinitve: "To shoot",
    past: "Shot",
    pastParticiple: "Shot",
    audioName: "to_shoot.mp3",
  }),
  new IrregularVerb({
    id: 60,
    translation: "Cantar",
    infinitve: "To sing",
    past: "Sang",
    pastParticiple: "Sung",
    audioName: "to_sing.mp3",
  }),
  new IrregularVerb({
    id: 61,
    translation: "Sentar",
    infinitve: "To sit",
    past: "Sat",
    pastParticiple: "Sat",
    audioName: "to_sit.mp3",
  }),
  new IrregularVerb({
    id: 62,
    translation: "Dormir",
    infinitve: "To sleep",
    past: "Slept",
    pastParticiple: "Slept",
    audioName: "to_sleep.mp3",
  }),
  new IrregularVerb({
    id: 63,
    translation: "Falar",
    infinitve: "To speak",
    past: "Spoke",
    pastParticiple: "Spoken",
    audioName: "to_speak.mp3",
  }),
  new IrregularVerb({
    id: 64,
    translation: "Passar / Gastar",
    infinitve: "To spend",
    past: "Spent",
    pastParticiple: "Spent",
    audioName: "to_spend.mp3",
  }),
  new IrregularVerb({
    id: 65,
    translation: "Ficar em pé",
    infinitve: "To stand",
    past: "Stood",
    pastParticiple: "Stood",
    audioName: "to_stand.mp3",
  }),
  new IrregularVerb({
    id: 66,
    translation: "Roubar",
    infinitve: "To steal",
    past: "Stole",
    pastParticiple: "Stolen",
    audioName: "to_steal.mp3",
  }),
  new IrregularVerb({
    id: 67,
    translation: "Varrer",
    infinitve: "To sweep",
    past: "Swept",
    pastParticiple: "Swept",
    audioName: "to_sweep.mp3",
  }),
  new IrregularVerb({
    id: 68,
    translation: "Nadar",
    infinitve: "To swim",
    past: "Swam",
    pastParticiple: "Swum",
    audioName: "to_swim.mp3",
  }),
  new IrregularVerb({
    id: 69,
    translation: "Tomar / Levar / Pegar / Tirar",
    infinitve: "To take",
    past: "Took",
    pastParticiple: "Taken",
    audioName: "to_take.mp3",
  }),
  new IrregularVerb({
    id: 70,
    translation: "Ensinar",
    infinitve: "To teach",
    past: "Taught",
    pastParticiple: "Taught",
    audioName: "to_teach.mp3",
  }),
  new IrregularVerb({
    id: 71,
    translation: "Rasgar",
    infinitve: "To tear",
    past: "Tore",
    pastParticiple: "Torn",
    audioName: "to_tear.mp3",
  }),
  new IrregularVerb({
    id: 72,
    translation: "Dizer / Contar",
    infinitve: "To tell",
    past: "Told",
    pastParticiple: "Told",
    audioName: "to_tell.mp3",
  }),
  new IrregularVerb({
    id: 73,
    translation: "Pensar / Achar",
    infinitve: "To think",
    past: "Thought",
    pastParticiple: "Thought",
    audioName: "to_think.mp3",
  }),
  new IrregularVerb({
    id: 74,
    translation: "Arremessar / Jogar",
    infinitve: "To throw",
    past: "Threw",
    pastParticiple: "Thrown",
    audioName: "to_throw.mp3",
  }),
  new IrregularVerb({
    id: 75,
    translation: "Entender",
    infinitve: "To understand",
    past: "Understood",
    pastParticiple: "Understood",
    audioName: "to_understand.mp3",
  }),
  new IrregularVerb({
    id: 76,
    translation: "Acordar",
    infinitve: "To wake up",
    past: "Woke up",
    pastParticiple: "Woken up",
    audioName: "to_wake_up.mp3",
  }),
  new IrregularVerb({
    id: 77,
    translation: "Molhar",
    infinitve: "To wet",
    past: "Wet",
    pastParticiple: "Wet",
    audioName: "to_wet.mp3",
  }),
  new IrregularVerb({
    id: 78,
    translation: "Ganhar / Vencer",
    infinitve: "To win",
    past: "Won",
    pastParticiple: "Won",
    audioName: "to_win.mp3",
  }),
  new IrregularVerb({
    id: 79,
    translation: "Escrever",
    infinitve: "To write",
    past: "Wrote",
    pastParticiple: "Written",
    audioName: "to_write.mp3",
  }),
  new IrregularVerb({
    id: 80,
    translation: "Vestir / Usar",
    infinitve: "To wear",
    past: "Wore",
    pastParticiple: "Worn",
    audioName: "to_wear.mp3",
  }),
];

export { IrregularVerbDatabase };
