import { OnPronounciation } from "../modules/onPronounciations/entities/OnPronounciation";

const OnPronounciationsDatabase: Array<OnPronounciation> = [
  {
    id: 1,
    subject: "I",
    auxiliaryVerb: "do",
    pronounciation: "Duái",
    audioName: "do_i.mp3",
  },
  {
    id: 2,
    subject: "You",
    auxiliaryVerb: "do",
    pronounciation: "Diu",
    audioName: "do_you.mp3",
  },
  {
    id: 3,
    subject: "He",
    auxiliaryVerb: "does",
    pronounciation: "Dázi",
    audioName: "does_he.mp3",
  },
  {
    id: 4,
    subject: "She",
    auxiliaryVerb: "does",
    pronounciation: "Dáshi",
    audioName: "does_she.mp3",
  },
  {
    id: 5,
    subject: "It",
    auxiliaryVerb: "does",
    pronounciation: "Dázêt",
    audioName: "does_it.mp3",
  },
  {
    id: 6,
    subject: "We",
    auxiliaryVerb: "do",
    pronounciation: "Duí",
    audioName: "do_we.mp3",
  },
  {
    id: 7,
    subject: "You",
    auxiliaryVerb: "do",
    pronounciation: "Diu",
    audioName: "do_you.mp3",
  },
  {
    id: 8,
    subject: "They",
    auxiliaryVerb: "do",
    pronounciation: "Dúdei / Dúrei",
    audioName: "do_they.mp3",
  },
  {
    id: 8,
    subject: "I",
    auxiliaryVerb: "did",
    pronounciation: "Dêdai / Dêrai",
    audioName: "did_i.mp3",
  },
  {
    id: 9,
    subject: "You",
    auxiliaryVerb: "did",
    pronounciation: "Dêdju",
    audioName: "did_you.mp3",
  },
  {
    id: 10,
    subject: "He",
    auxiliaryVerb: "did",
    pronounciation: "Dêri",
    audioName: "did_he.mp3",
  },
  {
    id: 11,
    subject: "She",
    auxiliaryVerb: "did",
    pronounciation: "Dêdshi",
    audioName: "did_she.mp3",
  },
  {
    id: 12,
    subject: "It",
    auxiliaryVerb: "did",
    pronounciation: "Dêrêt",
    audioName: "did_it.mp3",
  },
  {
    id: 13,
    subject: "We",
    auxiliaryVerb: "did",
    pronounciation: "Dêdui",
    audioName: "did_we.mp3",
  },
  {
    id: 14,
    subject: "You",
    auxiliaryVerb: "did",
    pronounciation: "Dêdju",
    audioName: "did_you.mp3",
  },
  {
    id: 15,
    subject: "They",
    auxiliaryVerb: "did",
    pronounciation: "DêDei / Dêrei",
    audioName: "did_they.mp3",
  },
];

export { OnPronounciationsDatabase };
