import { PresentPerfect } from "../modules/presentPerfect/entities/PresentPerfect";

const PresentPerfectDatabase: Array<PresentPerfect> = [
  new PresentPerfect({
    id: 1,
    typeId: 1,
    verb: "got",
    subject: "I",
    auxiliaryVerb: "have",
  }),
  new PresentPerfect({
    id: 2,
    typeId: 1,
    verb: "got",
    subject: "You",
    auxiliaryVerb: "have",
  }),
  new PresentPerfect({
    id: 3,
    typeId: 1,
    verb: "got",
    subject: "He",
    auxiliaryVerb: "has",
  }),
  new PresentPerfect({
    id: 4,
    typeId: 1,
    verb: "got",
    subject: "She",
    auxiliaryVerb: "has",
  }),
  new PresentPerfect({
    id: 5,
    typeId: 1,
    verb: "got",
    subject: "It",
    auxiliaryVerb: "has",
  }),
  new PresentPerfect({
    id: 6,
    typeId: 1,
    verb: "got",
    subject: "We",
    auxiliaryVerb: "have",
  }),
  new PresentPerfect({
    id: 7,
    typeId: 1,
    verb: "got",
    subject: "You",
    auxiliaryVerb: "have",
  }),
  new PresentPerfect({
    id: 8,
    typeId: 1,
    verb: "got",
    subject: "They",
    auxiliaryVerb: "have",
  }),
  new PresentPerfect({
    id: 9,
    typeId: 2,
    verb: "got",
    subject: "I",
    auxiliaryVerb: "'ve",
  }),
  new PresentPerfect({
    id: 10,
    typeId: 2,
    verb: "got",
    subject: "You",
    auxiliaryVerb: "'ve",
  }),
  new PresentPerfect({
    id: 11,
    typeId: 2,
    verb: "got",
    subject: "He",
    auxiliaryVerb: "'s",
  }),
  new PresentPerfect({
    id: 12,
    typeId: 2,
    verb: "got",
    subject: "She",
    auxiliaryVerb: "'s",
  }),
  new PresentPerfect({
    id: 13,
    typeId: 2,
    verb: "got",
    subject: "It",
    auxiliaryVerb: "'s",
  }),
  new PresentPerfect({
    id: 14,
    typeId: 2,
    verb: "got",
    subject: "We",
    auxiliaryVerb: "'ve",
  }),
  new PresentPerfect({
    id: 15,
    typeId: 2,
    verb: "got",
    subject: "You",
    auxiliaryVerb: "'ve",
  }),
  new PresentPerfect({
    id: 15,
    typeId: 2,
    verb: "got",
    subject: "They",
    auxiliaryVerb: "'ve",
  }),
];

export { PresentPerfectDatabase };
